{{ config(materialized='view') }}

SELECT
  unique_row_id as PK,
  filename,
  event_id,
  episode_id,
  state,
  state_fips_code,
  event_type,
  cz_type,
  cz_fips_code,
  cz_name,
  wfo,
  event_begin_time,
  event_end_time,
  event_timezone,
  injuries_direct,
  injuries_indirect,
  deaths_direct,
  deaths_indirect,
  damage_property,
  damage_crops,
  source,
  magnitude,
  magnitude_type,
  flood_cause,
  tor_f_scale,
  tor_length,
  tor_width,
  tor_other_wfo,
  location_index,
  event_range,
  event_azimuth,
  reference_location,
  event_latitude,
  event_longitude
FROM `{{ target.project }}.{{ target.schema }}.noaa_storms_fact`
